name: mdcanbdm042-2025
region: fra1

databases:
- cluster_name: astrobsmvelvet-db
  db_name: defaultdb
  db_user: mdcanconfreg
  engine: PG
  name: astrobsmvelvet-db
  production: true
  version: "17"

envs:
- key: DATABASE_URL
  scope: RUN_TIME
  value: ${astrobsmvelvet-db.DATABASE_URL}

- key: EMAIL_HOST
  scope: RUN_AND_BUILD_TIME
  value: smtp.gmail.com
- key: EMAIL_PORT
  scope: RUN_AND_BUILD_TIME
  value: "587"
- key: EMAIL_USER
  scope: RUN_AND_BUILD_TIME
  value: mdcanenugu@gmail.com
- key: EMAIL_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:Orzjes4NjWQpKh+uzahH7F/LPIG+JhO6:2f4gbw3X+yomf77NYOSDiECfI97hbek0NdPSRmgwXTD4ddE=]
- key: EMAIL_FROM
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:IUO26D59WkVP+axQBnQUNLwB/pcllViK:DuOr4bod92jmKgw/ZjXpIaeCMWv8VILqon7IbHa6bSk+pyXNmgFHysF3CE+HY7CQA8yhfXM=]

features:
- buildpack-stack=ubuntu-22

ingress:
  rules:
  - component:
      name: mdcanreg-cert
    match:
      authority:
        exact: "mdcanbdm042-2025-tdlv8.ondigitalocean.app"  # Using your current DO domain
      path:
        prefix: /

services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: astrobsm/mdcanreg_cert
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: mdcanreg-cert
  run_command: gunicorn --bind 0.0.0.0:${PORT:-8080} digital_ocean_app:app
  source_dir: /
